name: my-workflow-name

on:
  push:
    branches: [ gadji ]
  pull_request:
    branches: [ gadji ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: rm -r _build && cmake -H. -B_build -DBUILD_TESTS=ON && cmake --build _build
    - name: test
      run: cmake --build _build --target test -- ARGS=--verbose
